### ISSUE TITLE
Query string params

### ISSUE THREAD

**Issue by aivus** [boo1ean/apiapi#2]
Some github requests require `access_token` param in query string, but now it's not possible for POST requests.

I think it should be possible to add params to query string. Like
`POST /repos/{owner}/{repo}/hooks?access_token={accessToken}`

**Comment by boo1ean** [comment]
As a variant you can bundle you access_token into urls at api client build time:

``` js
new ApiClient({
  methods: {
    issues: 'post /issues?access_token=' + config.access_token
  }
})
```

Not the best way, but should work.

Also your proposal seems good for me.

**Comment by aivus** [comment]
Access token is depend of user. It stored in DB. In this case I should recreate ApiClient after receive it from DB.
