### ISSUE TITLE
Add additional request params to apiMethod

### ISSUE THREAD

**Issue by aivus** [boo1ean/apiapi#4]
@boo1ean, what do you think about add second parameter to `apiMethod`.
For example, we can set additional headers to request.

```
apiClient.method({
    param: 'someParam'
}, {
    headers: {
        Authentication: "token GITHUB-TOKEN"
    }
});
```

This can resolve problem with usage github api.

**Comment by boo1ean** [comment]
Usually your headers for any of api requests to the same api server will be constant, so that's why you want pass headers overrides to constructor. see readme example https://github.com/boo1ean/apiapi#example-usage

Or do I miss some cases?

**Comment by aivus** [comment]
Case like this:
https://developer.github.com/v3/auth/#working-with-two-factor-authentication

**Comment by aivus** [comment]
What do you think about this approach?

I have some changes for this already:
https://github.com/aivus/apiapi/commit/7dbf6bb4b16b2fea4a4703bc2afa8b668c362d43

**Comment by boo1ean** [comment]
ok for me, also you can kill

``` js
requestOptions = _.clone(requestOptions);
```
