### ISSUE TITLE
PUT request support

### ISSUE THREAD

**Issue by rymohr** [boo1ean/apiapi#7]
Thanks for the library! Is there a reason you left out support for PUT requests?

https://github.com/boo1ean/apiapi/blob/079a7a1f03b07c86f9c5d9ddc6759d3341d20aa7/index.js#L66

**Comment by boo1ean** [comment]
Hmm, I guess I just didn't use. Will fix it now, thanks!

**Comment by boo1ean** [comment]
added in apiapi@0.3.6
