### ISSUE TITLE
DELETE request support

### ISSUE THREAD

**Issue by rymohr** [boo1ean/apiapi#8]
Shouldn't `opts.json = true` for DELETE requests too? Without that responses will be raw strings instead of objects.

Is there any reason `opts.json` shouldn't be `true` by default for all requests?

https://github.com/boo1ean/apiapi/blob/0388a20ed79bfb4b6f65a83134e4ba2ed8ee3399/index.js#L66

**Comment by boo1ean** [comment]
Added delete method  https://github.com/boo1ean/apiapi/commit/7f4e0353713824bccaf17911c644d0ae0d546071

**Comment by rymohr** [comment]
Thanks @boo1ean.  I've never seen a DELETE request that passed anything through the body but I guess it can't hurt.
